pipeline {
    agent any
    /*
    environment {
		DOCKERHUB_CREDENTIALS=credentials('docker-cred')
		YOUR_DOCKERHUB_USERNAME="amidshukurov"
        SERVICE_NAME = "frontend-app-service"
        REPOSITORY_TAG="${YOUR_DOCKERHUB_USERNAME}/${SERVICE_NAME}:${BUILD_ID}"
	}
    */
    stages {
        stage('Build docker image') {
            steps {
                sh 'docker build --file frontend/Dockerfile -t amidshukurov/frontend-app:01 frontend/'
            }
        }
        stage('Login to DockerHub') {
			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u finalse --password-Amid-21392139'
			}
		}
        stage('Push docker image to registry') {
            steps {
                sh 'docker push amidshukurov/frontend-app:01'
            }
        }
        stage('Deploy to Cluster') {
          steps {
                sh 'envsubst < ${WORKSPACE}/frontend/deploy.yaml | kubectl apply -f -'
            }
        }
    }
}
